// Model presets — frontend hardcoded, no backend interaction.
// Source values verified against official model docs (2025-07).
// Cost fields are all 0 by design — users fill those in manually.

import type { Model } from './types'

export interface ModelPreset {
  label: string
  model: Model
}

export const MODEL_PRESETS: ModelPreset[] = [
  {
    label: 'GPT-4o',
    model: {
      id: 'gpt-4o',
      name: 'GPT-4o',
      reasoning: false,
      inputText: true,
      inputImage: true,
      contextWindow: 128000,
      maxTokens: 16384,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'GPT-4o-mini',
    model: {
      id: 'gpt-4o-mini',
      name: 'GPT-4o-mini',
      reasoning: false,
      inputText: true,
      inputImage: true,
      contextWindow: 128000,
      maxTokens: 16384,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'GPT-4.1',
    model: {
      id: 'gpt-4.1',
      name: 'GPT-4.1',
      reasoning: false,
      inputText: true,
      inputImage: true,
      contextWindow: 1000000,
      maxTokens: 32768,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'GPT-4.1-mini',
    model: {
      id: 'gpt-4.1-mini',
      name: 'GPT-4.1-mini',
      reasoning: false,
      inputText: true,
      inputImage: true,
      contextWindow: 1000000,
      maxTokens: 32768,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'Claude Sonnet 4.5',
    model: {
      id: 'claude-sonnet-4-5',
      name: 'Claude Sonnet 4.5',
      reasoning: true,
      inputText: true,
      inputImage: true,
      contextWindow: 200000,
      maxTokens: 8192,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'Claude Opus 4.5',
    model: {
      id: 'claude-opus-4-5',
      name: 'Claude Opus 4.5',
      reasoning: true,
      inputText: true,
      inputImage: true,
      contextWindow: 200000,
      maxTokens: 8192,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'Claude Haiku 4.5',
    model: {
      id: 'claude-haiku-4-5',
      name: 'Claude Haiku 4.5',
      reasoning: false,
      inputText: true,
      inputImage: false,
      contextWindow: 200000,
      maxTokens: 8192,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'Gemini 2.5 Pro',
    model: {
      id: 'gemini-2.5-pro',
      name: 'Gemini 2.5 Pro',
      reasoning: false,
      inputText: true,
      inputImage: true,
      contextWindow: 1048576,
      maxTokens: 65536,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'Gemini 2.5 Flash',
    model: {
      id: 'gemini-2.5-flash',
      name: 'Gemini 2.5 Flash',
      reasoning: false,
      inputText: true,
      inputImage: true,
      contextWindow: 1048576,
      maxTokens: 65536,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'DeepSeek V3',
    model: {
      id: 'deepseek-chat',
      name: 'DeepSeek V3',
      reasoning: false,
      inputText: true,
      inputImage: false,
      contextWindow: 128000,
      maxTokens: 8192,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
  {
    label: 'DeepSeek R1',
    model: {
      id: 'deepseek-reasoner',
      name: 'DeepSeek R1',
      reasoning: true,
      inputText: true,
      inputImage: false,
      contextWindow: 128000,
      maxTokens: 8192,
      costInput: 0,
      costOutput: 0,
      costCacheRead: 0,
      costCacheWrite: 0,
    },
  },
]
