// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBuiltInProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddCustomProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddModel(arg1:string,arg2:main.Model):Promise<void>;

export function ExportConfig():Promise<void>;

export function FetchProviderModels(arg1:string):Promise<Array<main.Model>>;

export function GetConfig():Promise<main.Config>;

export function ImportConfig():Promise<void>;

export function ImportProviderModels(arg1:string,arg2:Array<main.Model>):Promise<number>;

export function ListAPITypes():Promise<Array<string>>;

export function ListBuiltInProviders():Promise<Array<main.BuiltInProvider>>;

export function LoadSSHAddress():Promise<string>;

export function RemoveModel(arg1:string,arg2:string):Promise<void>;

export function RemoveModels(arg1:string,arg2:Array<string>):Promise<number>;

export function RemoveProvider(arg1:string):Promise<void>;

export function ReorderModels(arg1:string,arg2:Array<string>):Promise<void>;

export function ReorderProviders(arg1:Array<string>):Promise<void>;

export function SaveSSHAddress(arg1:string):Promise<void>;

export function SetProviderEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SyncPiConfig(arg1:string):Promise<main.SyncResult>;

export function TestProviderConnectivity(arg1:string):Promise<string>;

export function TestSSHConnection(arg1:string):Promise<main.SSHConnectionResult>;

export function UpdateModel(arg1:string,arg2:main.Model):Promise<void>;

export function UpdateProvider(arg1:main.Provider):Promise<void>;
