// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBuiltInProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBuiltInProvider'](arg1, arg2, arg3);
}

export function AddCustomProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddCustomProvider'](arg1, arg2, arg3, arg4);
}

export function AddModel(arg1, arg2) {
  return window['go']['main']['App']['AddModel'](arg1, arg2);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function FetchProviderModels(arg1) {
  return window['go']['main']['App']['FetchProviderModels'](arg1);
}

export function GetCbmRules() {
  return window['go']['main']['App']['GetCbmRules']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPiPackages() {
  return window['go']['main']['App']['GetPiPackages']();
}

export function GetPiVersion() {
  return window['go']['main']['App']['GetPiVersion']();
}

export function GetRemotePiPackages(arg1) {
  return window['go']['main']['App']['GetRemotePiPackages'](arg1);
}

export function GetRemotePiVersion(arg1) {
  return window['go']['main']['App']['GetRemotePiVersion'](arg1);
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function ImportProviderModels(arg1, arg2) {
  return window['go']['main']['App']['ImportProviderModels'](arg1, arg2);
}

export function InstallPiPackage(arg1) {
  return window['go']['main']['App']['InstallPiPackage'](arg1);
}

export function InstallRemotePiPackage(arg1, arg2) {
  return window['go']['main']['App']['InstallRemotePiPackage'](arg1, arg2);
}

export function ListAPITypes() {
  return window['go']['main']['App']['ListAPITypes']();
}

export function ListBuiltInProviders() {
  return window['go']['main']['App']['ListBuiltInProviders']();
}

export function LoadSSHAddress() {
  return window['go']['main']['App']['LoadSSHAddress']();
}

export function RemoveModel(arg1, arg2) {
  return window['go']['main']['App']['RemoveModel'](arg1, arg2);
}

export function RemoveModels(arg1, arg2) {
  return window['go']['main']['App']['RemoveModels'](arg1, arg2);
}

export function RemovePiPackage(arg1) {
  return window['go']['main']['App']['RemovePiPackage'](arg1);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RemoveRemotePiPackage(arg1, arg2) {
  return window['go']['main']['App']['RemoveRemotePiPackage'](arg1, arg2);
}

export function ReorderModels(arg1, arg2) {
  return window['go']['main']['App']['ReorderModels'](arg1, arg2);
}

export function ReorderProviders(arg1) {
  return window['go']['main']['App']['ReorderProviders'](arg1);
}

export function SaveSSHAddress(arg1) {
  return window['go']['main']['App']['SaveSSHAddress'](arg1);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProviderEnabled'](arg1, arg2);
}

export function SyncPiConfig(arg1) {
  return window['go']['main']['App']['SyncPiConfig'](arg1);
}

export function TestProviderConnectivity(arg1) {
  return window['go']['main']['App']['TestProviderConnectivity'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function UpdateAllPiPackages() {
  return window['go']['main']['App']['UpdateAllPiPackages']();
}

export function UpdateModel(arg1, arg2) {
  return window['go']['main']['App']['UpdateModel'](arg1, arg2);
}

export function UpdatePiPackage(arg1) {
  return window['go']['main']['App']['UpdatePiPackage'](arg1);
}

export function UpdatePiSelf() {
  return window['go']['main']['App']['UpdatePiSelf']();
}

export function UpdateProvider(arg1) {
  return window['go']['main']['App']['UpdateProvider'](arg1);
}

export function UpdateRemoteAllPiPackages(arg1) {
  return window['go']['main']['App']['UpdateRemoteAllPiPackages'](arg1);
}

export function UpdateRemotePiPackage(arg1, arg2) {
  return window['go']['main']['App']['UpdateRemotePiPackage'](arg1, arg2);
}

export function UpdateRemotePiSelf(arg1) {
  return window['go']['main']['App']['UpdateRemotePiSelf'](arg1);
}
