// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateScheme(arg1) {
  return window['go']['main']['App']['ActivateScheme'](arg1);
}

export function AddBuiltInProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddBuiltInProvider'](arg1, arg2, arg3, arg4);
}

export function AddCustomProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCustomProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function AddModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddModel'](arg1, arg2, arg3);
}

export function CreateScheme(arg1) {
  return window['go']['main']['App']['CreateScheme'](arg1);
}

export function DeleteScheme(arg1) {
  return window['go']['main']['App']['DeleteScheme'](arg1);
}

export function DuplicateScheme(arg1) {
  return window['go']['main']['App']['DuplicateScheme'](arg1);
}

export function ExportSchemes() {
  return window['go']['main']['App']['ExportSchemes']();
}

export function FetchProviderModels(arg1, arg2) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2);
}

export function GetActiveSchemeID() {
  return window['go']['main']['App']['GetActiveSchemeID']();
}

export function ImportProviderModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportProviderModels'](arg1, arg2, arg3);
}

export function ImportSchemes() {
  return window['go']['main']['App']['ImportSchemes']();
}

export function ListAPITypes() {
  return window['go']['main']['App']['ListAPITypes']();
}

export function ListBuiltInProviders() {
  return window['go']['main']['App']['ListBuiltInProviders']();
}

export function ListSchemes() {
  return window['go']['main']['App']['ListSchemes']();
}

export function LoadSSHAddress() {
  return window['go']['main']['App']['LoadSSHAddress']();
}

export function RemoveModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveModel'](arg1, arg2, arg3);
}

export function RemoveProvider(arg1, arg2) {
  return window['go']['main']['App']['RemoveProvider'](arg1, arg2);
}

export function SaveSSHAddress(arg1) {
  return window['go']['main']['App']['SaveSSHAddress'](arg1);
}

export function SyncPiConfig(arg1) {
  return window['go']['main']['App']['SyncPiConfig'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function UpdateModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateModel'](arg1, arg2, arg3);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateScheme(arg1) {
  return window['go']['main']['App']['UpdateScheme'](arg1);
}
