// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBuiltInProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBuiltInProvider'](arg1, arg2, arg3);
}

export function AddCustomProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddCustomProvider'](arg1, arg2, arg3, arg4);
}

export function AddModel(arg1, arg2) {
  return window['go']['main']['App']['AddModel'](arg1, arg2);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function FetchProviderModels(arg1) {
  return window['go']['main']['App']['FetchProviderModels'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function ImportProviderModels(arg1, arg2) {
  return window['go']['main']['App']['ImportProviderModels'](arg1, arg2);
}

export function ListAPITypes() {
  return window['go']['main']['App']['ListAPITypes']();
}

export function ListBuiltInProviders() {
  return window['go']['main']['App']['ListBuiltInProviders']();
}

export function LoadSSHAddress() {
  return window['go']['main']['App']['LoadSSHAddress']();
}

export function RemoveModel(arg1, arg2) {
  return window['go']['main']['App']['RemoveModel'](arg1, arg2);
}

export function RemoveModels(arg1, arg2) {
  return window['go']['main']['App']['RemoveModels'](arg1, arg2);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function ReorderModels(arg1, arg2) {
  return window['go']['main']['App']['ReorderModels'](arg1, arg2);
}

export function ReorderProviders(arg1) {
  return window['go']['main']['App']['ReorderProviders'](arg1);
}

export function SaveSSHAddress(arg1) {
  return window['go']['main']['App']['SaveSSHAddress'](arg1);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProviderEnabled'](arg1, arg2);
}

export function SyncPiConfig(arg1) {
  return window['go']['main']['App']['SyncPiConfig'](arg1);
}

export function TestProviderConnectivity(arg1) {
  return window['go']['main']['App']['TestProviderConnectivity'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function UpdateModel(arg1, arg2) {
  return window['go']['main']['App']['UpdateModel'](arg1, arg2);
}

export function UpdateProvider(arg1) {
  return window['go']['main']['App']['UpdateProvider'](arg1);
}
