// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateScheme(arg1:string):Promise<void>;

export function AddBuiltInProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddCustomProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddModel(arg1:string,arg2:string,arg3:main.Model):Promise<void>;

export function CreateScheme(arg1:string):Promise<main.Scheme>;

export function DeleteScheme(arg1:string):Promise<void>;

export function DuplicateScheme(arg1:string):Promise<main.Scheme>;

export function ExportSchemes():Promise<void>;

export function FetchProviderModels(arg1:string,arg2:string):Promise<Array<main.Model>>;

export function GetActiveSchemeID():Promise<string>;

export function ImportProviderModels(arg1:string,arg2:string,arg3:Array<main.Model>):Promise<number>;

export function ImportSchemes():Promise<void>;

export function ListAPITypes():Promise<Array<string>>;

export function ListBuiltInProviders():Promise<Array<main.BuiltInProvider>>;

export function ListSchemes():Promise<Array<main.Scheme>>;

export function LoadSSHAddress():Promise<string>;

export function RemoveModel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveProvider(arg1:string,arg2:string):Promise<void>;

export function SaveSSHAddress(arg1:string):Promise<void>;

export function SyncPiConfig(arg1:string):Promise<main.SyncResult>;

export function TestSSHConnection(arg1:string):Promise<main.SSHConnectionResult>;

export function UpdateModel(arg1:string,arg2:string,arg3:main.Model):Promise<void>;

export function UpdateProvider(arg1:string,arg2:main.Provider):Promise<void>;

export function UpdateScheme(arg1:main.Scheme):Promise<void>;
